[build]
  command```
  command = "npm start"  # Команда для збірки вашого проекту, якщо потрібно

[functions]
  directory = "functions"  # Шлях до каталогу з функціями

[[redirects]]
  from = "/*"  # Шаблон URL, на який буде спрацьовувати редирект
  to = "/"  # Шлях до головного HTML-файлу вашого проекту
  status = 200 